import type { Provider } from "../schema.js";

/**
 * Generates the content for lib/llm.ts to be written into the user's project.
 * Uses fetch only — no AI SDKs.
 */
export function generateLlmFile(provider: Provider, selectedModel?: string): string {
  const model = (selectedModel?.trim() || provider.defaultModel).trim();
  if (provider.anthropicFormat) return generateAnthropicLlm(provider, model);
  if (provider.googleFormat) return generateGoogleLlm(provider, model);
  if (provider.bedrockFormat) return generateBedrockLlm(provider, model);
  return generateOpenAICompatibleLlm(provider, model);
}

// ---------------------------------------------------------------------------
// OpenAI-compatible (OpenAI, OpenRouter, Groq, Together, Mistral, xAI,
//                    DeepSeek, Cerebras, Fireworks)
// ---------------------------------------------------------------------------

function generateOpenAICompatibleLlm(provider: Provider, model: string): string {
  const apiKeyEnv = provider.env[0];
  return `// lib/llm.ts — generated by chatcn (${provider.label})
// Provider: ${provider.label} | Model: ${model}
// Docs: ${provider.baseURL}

export type Message = { role: "user" | "assistant" | "system"; content: string };

const BASE_URL = "${provider.baseURL}";
const MODEL = process.env.AI_MODEL ?? ${JSON.stringify(model)};
const API_KEY = process.env.${apiKeyEnv};

/**
 * Streams a chat completion from ${provider.label}.
 * Yields plain text chunks as they arrive.
 */
export async function streamChat(
  messages: Message[],
  signal?: AbortSignal
): Promise<ReadableStream<string>> {
  if (!API_KEY) throw new Error("${apiKeyEnv} is not set");

  const res = await fetch(\`\${BASE_URL}/chat/completions\`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: \`Bearer \${API_KEY}\`,
    },
    body: JSON.stringify({ model: MODEL, messages, stream: true }),
    signal,
  });

  if (!res.ok || !res.body) {
    const text = await res.text();
    throw new Error(\`${provider.label} error \${res.status}: \${text}\`);
  }

  return res.body
    .pipeThrough(new TextDecoderStream())
    .pipeThrough(parseSseStream());
}

/** Parses Server-Sent Events and extracts delta content tokens. */
function parseSseStream(): TransformStream<string, string> {
  let buffer = "";
  return new TransformStream({
    transform(chunk, controller) {
      buffer += chunk;
      const lines = buffer.split("\\n");
      buffer = lines.pop() ?? "";
      for (const line of lines) {
        if (!line.startsWith("data: ")) continue;
        const data = line.slice(6).trim();
        if (data === "[DONE]") return;
        try {
          const json = JSON.parse(data) as {
            choices: { delta: { content?: string } }[];
          };
          const content = json.choices[0]?.delta?.content;
          if (content) controller.enqueue(content);
        } catch {
          // skip malformed chunks
        }
      }
    },
  });
}
`;
}

// ---------------------------------------------------------------------------
// Anthropic (Claude Messages API)
// ---------------------------------------------------------------------------

function generateAnthropicLlm(provider: Provider, model: string): string {
  return `// lib/llm.ts — generated by chatcn (${provider.label})
// Provider: Anthropic | Model: ${model}
// Docs: https://docs.anthropic.com/en/api/messages

export type Message = { role: "user" | "assistant"; content: string };

const MODEL = process.env.AI_MODEL ?? ${JSON.stringify(model)};
const API_KEY = process.env.ANTHROPIC_API_KEY;

/**
 * Streams a chat completion from Anthropic Claude.
 * Yields plain text chunks as they arrive.
 */
export async function streamChat(
  messages: Message[],
  signal?: AbortSignal
): Promise<ReadableStream<string>> {
  if (!API_KEY) throw new Error("ANTHROPIC_API_KEY is not set");

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({ model: MODEL, messages, max_tokens: 4096, stream: true }),
    signal,
  });

  if (!res.ok || !res.body) {
    const text = await res.text();
    throw new Error(\`Anthropic error \${res.status}: \${text}\`);
  }

  return res.body
    .pipeThrough(new TextDecoderStream())
    .pipeThrough(parseAnthropicSse());
}

function parseAnthropicSse(): TransformStream<string, string> {
  let buffer = "";
  return new TransformStream({
    transform(chunk, controller) {
      buffer += chunk;
      const lines = buffer.split("\\n");
      buffer = lines.pop() ?? "";
      for (const line of lines) {
        if (!line.startsWith("data: ")) continue;
        const data = line.slice(6).trim();
        try {
          const json = JSON.parse(data) as {
            type: string;
            delta?: { type: string; text?: string };
          };
          if (json.type === "content_block_delta" && json.delta?.text) {
            controller.enqueue(json.delta.text);
          }
        } catch {
          // skip malformed chunks
        }
      }
    },
  });
}
`;
}

// ---------------------------------------------------------------------------
// Google Gemini (generateContent streaming)
// ---------------------------------------------------------------------------

function generateGoogleLlm(provider: Provider, model: string): string {
  return `// lib/llm.ts — generated by chatcn (${provider.label})
// Provider: Google Gemini | Model: ${model}
// Docs: https://ai.google.dev/api/generate-content

export type Message = { role: "user" | "model"; content: string };

const MODEL = process.env.AI_MODEL ?? ${JSON.stringify(model)};
const API_KEY = process.env.GOOGLE_API_KEY;
const BASE_URL = "https://generativelanguage.googleapis.com/v1beta";

/**
 * Streams a chat completion from Google Gemini.
 * Yields plain text chunks as they arrive.
 */
export async function streamChat(
  messages: Message[],
  signal?: AbortSignal
): Promise<ReadableStream<string>> {
  if (!API_KEY) throw new Error("GOOGLE_API_KEY is not set");

  const contents = messages.map((m) => ({
    role: m.role,
    parts: [{ text: m.content }],
  }));

  const res = await fetch(
    \`\${BASE_URL}/models/\${MODEL}:streamGenerateContent?alt=sse&key=\${API_KEY}\`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ contents }),
      signal,
    }
  );

  if (!res.ok || !res.body) {
    const text = await res.text();
    throw new Error(\`Google error \${res.status}: \${text}\`);
  }

  return res.body
    .pipeThrough(new TextDecoderStream())
    .pipeThrough(parseGoogleSse());
}

function parseGoogleSse(): TransformStream<string, string> {
  let buffer = "";
  return new TransformStream({
    transform(chunk, controller) {
      buffer += chunk;
      const lines = buffer.split("\\n");
      buffer = lines.pop() ?? "";
      for (const line of lines) {
        if (!line.startsWith("data: ")) continue;
        const data = line.slice(6).trim();
        try {
          const json = JSON.parse(data) as {
            candidates: { content: { parts: { text?: string }[] } }[];
          };
          const text = json.candidates[0]?.content?.parts[0]?.text;
          if (text) controller.enqueue(text);
        } catch {
          // skip malformed chunks
        }
      }
    },
  });
}
`;
}

// ---------------------------------------------------------------------------
// AWS Bedrock (Converse streaming via SigV4)
// ---------------------------------------------------------------------------

function generateBedrockLlm(provider: Provider, model: string): string {
  return `// lib/llm.ts — generated by chatcn (AWS Bedrock)
// Provider: ${provider.label} | Model: ${model}
// Docs: https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html
// Install: npm install @aws-sdk/client-bedrock-runtime

import {
  BedrockRuntimeClient,
  ConverseStreamCommand,
} from "@aws-sdk/client-bedrock-runtime";

export type Message = { role: "user" | "assistant"; content: string };

const MODEL_ID = process.env.AI_MODEL ?? ${JSON.stringify(model)};

const client = new BedrockRuntimeClient({
  region: process.env.AWS_REGION ?? "us-east-1",
  // Credentials are picked up from env vars or ~/.aws/credentials automatically
});

/**
 * Streams a chat completion from AWS Bedrock via the Converse API.
 * Yields plain text chunks as they arrive.
 */
export async function streamChat(
  messages: Message[],
  signal?: AbortSignal
): Promise<ReadableStream<string>> {
  const bedrockMessages = messages.map((m) => ({
    role: m.role,
    content: [{ text: m.content }],
  }));

  const command = new ConverseStreamCommand({
    modelId: MODEL_ID,
    messages: bedrockMessages,
  });

  const { stream } = await client.send(command, { abortSignal: signal });

  return new ReadableStream<string>({
    async start(controller) {
      if (!stream) { controller.close(); return; }
      for await (const event of stream) {
        const text = event.contentBlockDelta?.delta?.text;
        if (text) controller.enqueue(text);
      }
      controller.close();
    },
  });
}
`;
}
